### ISSUE TITLE
Not Compatible with Redmine Version 4.1.1

### ISSUE THREAD

**Issue by l4rsV** [versatilecommunity/redmine_spent_time#3]
Hi,

this plugin is a nice feature and would be really helpfull to use with newer Redmine Versions.
I tried to install the communicty version, but end up with a failure:

Thanks for your help.
Regards,

hostaname:/var/www/redmine-4.1.1/plugins $ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /var/www/redmine-4.1.1)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateSptimes < ActiveRecord::Migration[4.2]
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:528:in `inherited'
/var/www/redmine-4.1.1/plugins/redmine_spent_time/db/migrate/001_create_sptimes.rb:1:in `<top (required)>'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:986:in `load_migration'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:982:in `migration'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1350:in `use_transaction?'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1342:in `ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `migrate'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:510:in `up'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:542:in `migrate_plugin'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:483:in `migrate'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:497:in `block in migrate'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:496:in `each'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:496:in `migrate'
/var/www/redmine-4.1.1/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/share/gems/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/share/gems/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateSptimes < ActiveRecord::Migration[4.2]
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:528:in `inherited'
/var/www/redmine-4.1.1/plugins/redmine_spent_time/db/migrate/001_create_sptimes.rb:1:in `<top (required)>'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:986:in `load_migration'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:982:in `migration'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1350:in `use_transaction?'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1342:in `ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `migrate'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:510:in `up'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:542:in `migrate_plugin'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:483:in `migrate'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:497:in `block in migrate'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:496:in `each'
/var/www/redmine-4.1.1/lib/redmine/plugin.rb:496:in `migrate'
/var/www/redmine-4.1.1/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/share/gems/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/share/gems/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/share/gems/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by versatilecommunity** [comment]
We are happy to introduce the Spent Time plugin version 0.3
Please download it from
https://www.redmine.org/plugins/redmine_spent_time_versatile
https://github.com/versatilecommunity/redmine_spent_time

Please rate this plugin at https://www.redmine.org/plugins/redmine_spent_time_versatile

Release Notes for 0.3
Features:
- Compatable with Redmine 4.1.x
- upgrade rails version 5

Customization:
For any Customization/Support, please contact us, our consulting team will be happy to help you
e-mail: versatilecommunity@gmail.com

**Comment by saiballo** [comment]
hi,
plan to migrate for redmine 4.2?

**Comment by versatilecommunity** [comment]
> hi, plan to migrate for redmine 4.2?

We have the plan to migrate the latest redmine version.
